### ISSUE TITLE
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:841)

### ISSUE THREAD

**Issue by snefedov** [CryptoFacilities/WebSocket-v1-Python#4]
can't connect to WS. The latest version don't work at all:
error from callback <bound method CfWebSocketMethods.__on_error of <cfWebSocketApiV1.CfWebSocketMethods object at 0x000000000304AA20>>: __on_error() takes 2 positional arguments but 3 were given

**Comment by CryptoAdmin** [comment]
Hi! Please make sure that you have the python library  websocket-client==0.54.0 .

**Comment by snefedov** [comment]
my bad. now works, thanks a lot!
